version: "3"

services:
  react-app:
    image: react-app
    ports:
      - "5173:5173"
    networks:
      - mern-app

  api-server:
    image: api-server
    ports:
      - "8092:8092"
    networks:
      - mern-app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
