services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - mern-app

  api-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    #   - "8092:8092"
    networks:
      - mern-app
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    ports:
      - "8092:8092"
    networks:
      - mern-app
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api-server

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
